import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import "../icons.css";
import MemberInfoPopup from "@/_components/MemberInfoPopup";
import VendorNotePopup from "@/_components/VendorNotePopup";
import GlobalLoader from "@/_components/GlobalLoader";
import Providers from "./providers";

const nunito_sans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Smart Office",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${nunito_sans.variable} antialiased`}
        suppressHydrationWarning
      >
        <Providers>
          <MemberInfoPopup />
          {children}
          <VendorNotePopup />
          <GlobalLoader />
        </Providers>
      </body>
    </html>
  );
}
