export const EVENTS_DETAIL_DATA = [
  {
    id: 1,
    title: "Summer Leadership Workshop",
    date: "7/20/2026",
    location: "Mountain Resort",
    portfolio: "Learning Portfolio",
    attendees: 50,
    format: "Interactive Workshop",
    theme: "Professional Development",
    totalBudget: 18500,
    actualExpense: 15000,
    notes: "Three-day intensive leadership development workshop",
    budgetDistribution: [
      { name: "Accommodation", value: 25, color: "#885df1" },
      { name: "Event Management", value: 15, color: "#5cbbf6" },
      { name: "Food & Beverages", value: 16, color: "#11b981" },
      { name: "Resource Cost", value: 6, color: "#3a7cf5" },
      { name: "Gifts & Gratuities", value: 4, color: "#f59e0b" },
      { name: "Travelling", value: 8, color: "#ec4899" },
      { name: "Other", value: 25, color: "#9ca3af" },
    ],
  },
  {
    id: 2,
    title: "Spring Networking Event",
    date: "6/15/2026",
    location: "Grand Hotel Ballroom",
    portfolio: "Learning Portfolio",
    attendees: 75,
    format: "Networking Session",
    theme: "Business Growth",
    totalBudget: 11500,
    actualExpense: 5000,
    notes: "Annual spring networking event for members and industry guests",
    budgetDistribution: [
      { name: "Venue", value: 30, color: "#885df1" },
      { name: "Catering", value: 25, color: "#11b981" },
      { name: "Marketing", value: 15, color: "#5cbbf6" },
      { name: "Gifts & Gratuities", value: 10, color: "#f59e0b" },
      { name: "Entertainment", value: 12, color: "#ec4899" },
      { name: "Other", value: 8, color: "#9ca3af" },
    ],
  },
  {
    id: 3,
    title: "Annual Company Retreat",
    date: "6/15/2026",
    location: "Grand Hotel Ballroom",
    portfolio: "Networking Portfolio",
    attendees: 80,
    format: "Team Retreat",
    theme: "Culture & Collaboration",
    totalBudget: 12000,
    actualExpense: 4500,
    notes: "Annual company retreat focused on team building and culture",
    budgetDistribution: [
      { name: "Accommodation", value: 35, color: "#885df1" },
      { name: "Food & Beverages", value: 20, color: "#11b981" },
      { name: "Activities", value: 20, color: "#5cbbf6" },
      { name: "Transport", value: 15, color: "#ec4899" },
      { name: "Other", value: 10, color: "#9ca3af" },
    ],
  },
];
